Make NumPy available:

In [1]:
import numpy as np

## Exercise 07.1 (indexing and timing)

Create two very long NumPy 1D-arrays (vectors) `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`; and
2. A `for` loop that computes the sum entry-by-entry

Compare the time required for the two approaches for arrays of different lengths (use a very long array for 
the timing). The values of the array entries are not important for this test. Use `%time` to report the time.

*Hint:* To loop over an array using indices, try a construction like:

In [3]:
x = np.ones(10)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i]*y[i])

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


#### (1) Add two arrays using built-in addition operator:

In [42]:
...
x = np.ones(1000000)
y = np.zeros(1000000) # defining 2 long arrays

%time z = x+y



CPU times: user 4.25 ms, sys: 4.22 ms, total: 8.47 ms
Wall time: 8.17 ms


#### (2) Add two arrays using own implementation:

In [43]:
...
def addition(a,b):
    z=0
    for i in range(len(a)):
        z += a[i]
        z += b[i]
    return z
%time slower = addition(x,y) # using an iterative function  is over 10x slower than adding the arrays in one
# this effect became more pronounced with larger numbers


CPU times: user 437 ms, sys: 6.86 ms, total: 443 ms
Wall time: 452 ms


### Optional extension: just-in-time (JIT) compilation

You will see a large difference in the time required between your NumPy and 'plain' Python implementations. This is due to Python being an *interpreted* language as opposed to a *compiled* language. A way to speed up plain Python implementions is to convert the interpreted Python code into compiled code. A tool for doing this is [Numba](https://numba.pydata.org/).

Below is an example using Numba and JIT to accelerate a computation:

In [ ]:
%pip -q install numba 
import numba
import math

def compute_sine_native(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z

@numba.jit
def compute_sine_jit(x):
    z = np.zeros(len(x))
    for i in range(len(z)):
        z[i] = math.sin(x[i])
    return z
    
x = np.ones(10000000)
%time z = compute_sine_native(x)
compute_sine_jit(x)
%time z = compute_sine_jit(x)

**Task:** Test if Numba can be used to accelerate your implementation that uses indexing to sum two arrays, and by how much.

In [ ]:
...

## Exercise 07.2 (member functions and slicing)

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

1. A function that takes a NumPy array of the raw scores and returns the scores as percentages, sorted from 
   lowest to highest (try using `scores.sort()`, where `scores` is a NumPy array holding the scores).
1. A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the 
   keys '`min`', '`max`' and '`mean`'. Use the NumPy array functions `min()`, `max()` and `mean()` to do the 
   computation, e.g. `max = scores.max()`.  
   
   Design your function for the min, max and mean to optionally exclude the highest and lowest scores from the 
   computation of the min, max and mean. 
   
   *Hint:* sort the array of scores and use array slicing to exclude
   the first and the last entries.

Use the scores 
```python
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
```
to test your functions.

In [15]:
def to_percentage_and_sort(scores):
    ...
    percentages = scores/0.6 # dividing by thus increases the maximum score/percentage to 100
    sorted_percentages = np.sort(percentages) # this uses a numpy function to sort the array
    return sorted_percentages
    
scores = np.array([58.0, 35.0, 24.0, 42, 7.8])
print(to_percentage_and_sort(scores))

def statistics(scores, exclude=False):
    ...
    sorted_percentages = np.sort(scores) # must sort percentages prior to removing first and last term, in order to remove highest and lowest term
    if exclude:
        chosen_percentages = sorted_percentages[1:-1] # removes first and last percentage
    else:
        chosen_percentages = sorted_percentages # does not remove first and last percentage
    min = chosen_percentages.min()
    max = chosen_percentages.max()
    mean = chosen_percentages.mean()
    # print(f"Minimum percentage: {min} \n Maximum percentage: {max} \n Mean: {mean}") as a test
    return{"min": float(min),"max": float(max), "mean": float(mean)} # converted to float since the np.float

statistics(scores)
    
    
    

[13.         40.         58.33333333 70.         96.66666667]


{'min': 7.8, 'max': 58.0, 'mean': 33.36}

In [16]:
## tests ##

scores = np.array([35.0, 58.0, 24.0, 42, 7.8])
assert np.isclose(to_percentage_and_sort(scores), [ 13.0, 40.0, 58.33333333,  70.0, 96.66666667]).all()

s0 = statistics(scores)
assert np.isclose(s0["min"], 7.8)
assert np.isclose(s0["mean"], 33.36)
assert np.isclose(s0["max"], 58.0)

s1 = statistics(scores, True)
assert np.isclose(s1["min"], 24.0)
assert np.isclose(s1["mean"], 33.666666666666666667)
assert np.isclose(s1["max"], 42.0)

## Exercise 07.3 (slicing)

For the two-dimensional array

In [18]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing for the below operations, printing the results to the screen to check. Try to use array slicing such that your code would still work if the dimensions of `A` were enlarged.

**Check your results carefully against hand computations.**

#### 1. Extract the third column as a 1D array

In [19]:
...
array1 = A[:,3]
print(array1)

[ 67.1   -3.33   4.11 323.22]


#### 2. Extract the first two rows as a 2D sub-array

In [20]:
...
array2 = A[0:2,:]
print(array2)

[[ 4.    7.   -2.43 67.1 ]
 [-4.   64.   54.7  -3.33]]


#### 3.  Extract the bottom-right $2 \times 2$ block as a 2D sub-array

In [21]:
...
array3 = A[2:,2:]
print(array3)

[[   3.64    4.11]
 [-113.2   323.22]]


#### 4. Sum the last column

In [24]:
...
total = sum(A[:,3])
print(total)

391.1


#### Compute transpose

Compute the transpose of `A` (search online to find the function/syntax to do this).

In [27]:
...
transposed = A.T # more simple than I thought
print(transposed)


[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


## Exercise 07.4 (optional extension)

In a previous exercise (04.5) you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html) to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program from the earlier exercise, and compare the computational time (using `%time`).

In [ ]:
from scipy import optimize

...